# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import WeatherService_pb2 as WeatherService__pb2


class WeatherServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateWeatherEvent = channel.unary_unary(
                '/weather_service.WeatherService/CreateWeatherEvent',
                request_serializer=WeatherService__pb2.WeatherEvent.SerializeToString,
                response_deserializer=WeatherService__pb2.StatusReply.FromString,
                )
        self.SearchEvents = channel.unary_unary(
                '/weather_service.WeatherService/SearchEvents',
                request_serializer=WeatherService__pb2.Query.SerializeToString,
                response_deserializer=WeatherService__pb2.WeatherEventList.FromString,
                )


class WeatherServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateWeatherEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WeatherServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateWeatherEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateWeatherEvent,
                    request_deserializer=WeatherService__pb2.WeatherEvent.FromString,
                    response_serializer=WeatherService__pb2.StatusReply.SerializeToString,
            ),
            'SearchEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchEvents,
                    request_deserializer=WeatherService__pb2.Query.FromString,
                    response_serializer=WeatherService__pb2.WeatherEventList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'weather_service.WeatherService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class WeatherService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateWeatherEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/weather_service.WeatherService/CreateWeatherEvent',
            WeatherService__pb2.WeatherEvent.SerializeToString,
            WeatherService__pb2.StatusReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SearchEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/weather_service.WeatherService/SearchEvents',
            WeatherService__pb2.Query.SerializeToString,
            WeatherService__pb2.WeatherEventList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
