# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WeatherService.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14WeatherService.proto\x12\x0fweather_service\"/\n\x08Location\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\"b\n\x05Query\x12\x11\n\x04\x64\x61te\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x30\n\x08location\x18\x02 \x01(\x0b\x32\x19.weather_service.LocationH\x01\x88\x01\x01\x42\x07\n\x05_dateB\x0b\n\t_location\"^\n\x0cWeatherEvent\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12+\n\x08location\x18\x02 \x01(\x0b\x32\x19.weather_service.Location\x12\x13\n\x0btemperature\x18\x03 \x01(\x01\"\x1d\n\x0bStatusReply\x12\x0e\n\x06status\x18\x01 \x01(\t\"M\n\x10WeatherEventList\x12\x39\n\x12weather_event_data\x18\x01 \x03(\x0b\x32\x1d.weather_service.WeatherEvent2\xb2\x01\n\x0eWeatherService\x12S\n\x12\x43reateWeatherEvent\x12\x1d.weather_service.WeatherEvent\x1a\x1c.weather_service.StatusReply\"\x00\x12K\n\x0cSearchEvents\x12\x16.weather_service.Query\x1a!.weather_service.WeatherEventList\"\x00\x42\x37\n\x1bio.grpc.examples.iotserviceB\x0fIoTServiceProtoP\x01\xa2\x02\x04TEMPb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WeatherService_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\033io.grpc.examples.iotserviceB\017IoTServiceProtoP\001\242\002\004TEMP'
  _LOCATION._serialized_start=41
  _LOCATION._serialized_end=88
  _QUERY._serialized_start=90
  _QUERY._serialized_end=188
  _WEATHEREVENT._serialized_start=190
  _WEATHEREVENT._serialized_end=284
  _STATUSREPLY._serialized_start=286
  _STATUSREPLY._serialized_end=315
  _WEATHEREVENTLIST._serialized_start=317
  _WEATHEREVENTLIST._serialized_end=394
  _WEATHERSERVICE._serialized_start=397
  _WEATHERSERVICE._serialized_end=575
# @@protoc_insertion_point(module_scope)
